// <auto-generated />
using IDesign.Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDesign.Access.Migrations
{
    [DbContext(typeof(DesignDbContext))]
    [Migration("20250809230721_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("IDesign.Access.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "USA City 1"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "USA City 2"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "USA City 3"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "USA City 4"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "USA City 5"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "USA City 6"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "USA City 7"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "USA City 8"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "USA City 9"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name = "USA City 10"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Name = "Canada City 1"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            Name = "Canada City 2"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 2,
                            Name = "Canada City 3"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 2,
                            Name = "Canada City 4"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 2,
                            Name = "Canada City 5"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 2,
                            Name = "Canada City 6"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            Name = "Canada City 7"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            Name = "Canada City 8"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 2,
                            Name = "Canada City 9"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 2,
                            Name = "Canada City 10"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 3,
                            Name = "Mexico City 1"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 3,
                            Name = "Mexico City 2"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 3,
                            Name = "Mexico City 3"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 3,
                            Name = "Mexico City 4"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 3,
                            Name = "Mexico City 5"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 3,
                            Name = "Mexico City 6"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 3,
                            Name = "Mexico City 7"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 3,
                            Name = "Mexico City 8"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 3,
                            Name = "Mexico City 9"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 3,
                            Name = "Mexico City 10"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 4,
                            Name = "Brazil City 1"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 4,
                            Name = "Brazil City 2"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 4,
                            Name = "Brazil City 3"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 4,
                            Name = "Brazil City 4"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 4,
                            Name = "Brazil City 5"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 4,
                            Name = "Brazil City 6"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 4,
                            Name = "Brazil City 7"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 4,
                            Name = "Brazil City 8"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 4,
                            Name = "Brazil City 9"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 4,
                            Name = "Brazil City 10"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 5,
                            Name = "Argentina City 1"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 5,
                            Name = "Argentina City 2"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 5,
                            Name = "Argentina City 3"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 5,
                            Name = "Argentina City 4"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 5,
                            Name = "Argentina City 5"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 5,
                            Name = "Argentina City 6"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 5,
                            Name = "Argentina City 7"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 5,
                            Name = "Argentina City 8"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 5,
                            Name = "Argentina City 9"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 5,
                            Name = "Argentina City 10"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 6,
                            Name = "Colombia City 1"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 6,
                            Name = "Colombia City 2"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 6,
                            Name = "Colombia City 3"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 6,
                            Name = "Colombia City 4"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 6,
                            Name = "Colombia City 5"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 6,
                            Name = "Colombia City 6"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 6,
                            Name = "Colombia City 7"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 6,
                            Name = "Colombia City 8"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 6,
                            Name = "Colombia City 9"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 6,
                            Name = "Colombia City 10"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 7,
                            Name = "Chile City 1"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 7,
                            Name = "Chile City 2"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 7,
                            Name = "Chile City 3"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 7,
                            Name = "Chile City 4"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 7,
                            Name = "Chile City 5"
                        },
                        new
                        {
                            Id = 66,
                            CountryId = 7,
                            Name = "Chile City 6"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 7,
                            Name = "Chile City 7"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 7,
                            Name = "Chile City 8"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 7,
                            Name = "Chile City 9"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 7,
                            Name = "Chile City 10"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 8,
                            Name = "Peru City 1"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 8,
                            Name = "Peru City 2"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 8,
                            Name = "Peru City 3"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 8,
                            Name = "Peru City 4"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 8,
                            Name = "Peru City 5"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 8,
                            Name = "Peru City 6"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 8,
                            Name = "Peru City 7"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 8,
                            Name = "Peru City 8"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 8,
                            Name = "Peru City 9"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 8,
                            Name = "Peru City 10"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 9,
                            Name = "Venezuela City 1"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 9,
                            Name = "Venezuela City 2"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 9,
                            Name = "Venezuela City 3"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 9,
                            Name = "Venezuela City 4"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 9,
                            Name = "Venezuela City 5"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 9,
                            Name = "Venezuela City 6"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 9,
                            Name = "Venezuela City 7"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 9,
                            Name = "Venezuela City 8"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 9,
                            Name = "Venezuela City 9"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 9,
                            Name = "Venezuela City 10"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 10,
                            Name = "Ecuador City 1"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 10,
                            Name = "Ecuador City 2"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 10,
                            Name = "Ecuador City 3"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 10,
                            Name = "Ecuador City 4"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 10,
                            Name = "Ecuador City 5"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 10,
                            Name = "Ecuador City 6"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 10,
                            Name = "Ecuador City 7"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 10,
                            Name = "Ecuador City 8"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 10,
                            Name = "Ecuador City 9"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 10,
                            Name = "Ecuador City 10"
                        });
                });

            modelBuilder.Entity("IDesign.Access.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ecuador"
                        });
                });

            modelBuilder.Entity("IDesign.Access.Entities.City", b =>
                {
                    b.HasOne("IDesign.Access.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("IDesign.Access.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
